# Generated by Django 4.0.5 on 2022-07-06 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('memo', models.TextField(blank=True)),
                ('done', models.BooleanField(default=False)),
                ('starred', models.BooleanField(default=False)),
                ('important', models.BooleanField(default=False)),
                ('priority', models.CharField(blank=True, choices=[('primary', 'default'), ('danger', 'danger'), ('warning', 'warning'), ('success', 'success')], default='primary', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('memo', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('private', models.BooleanField(default=False)),
                ('todos', models.ManyToManyField(blank=True, to='todo.todo')),
            ],
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, default='profile_photos/default.svg', upload_to='profile_photos/')),
                ('followers', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('todoLists', models.ManyToManyField(blank=True, related_name='users', to='todo.todolist')),
                ('todos', models.ManyToManyField(blank=True, to='todo.todo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
