# Generated by Django 4.0.5 on 2022-07-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_userlist_bio_alter_userlist_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
