# Generated by Django 4.0.3 on 2022-06-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_todolist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='priorty',
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(blank=True, choices=[('default', 'primary'), ('d', 'danger'), ('w', 'warning'), ('s', 'success')], default='default', max_length=10),
        ),
    ]
