# Generated by Django 4.0.3 on 2022-06-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_todo_priorty_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(blank=True, choices=[('primary', 'default'), ('danger', 'danger'), ('warning', 'warning'), ('success', 'success')], default='default', max_length=10),
        ),
    ]
