# Generated by Django 4.0.5 on 2022-07-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_todolist_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='followers',
            field=models.ManyToManyField(blank=True, to='todo.userlist'),
        ),
        migrations.AddField(
            model_name='userlist',
            name='following',
            field=models.ManyToManyField(blank=True, to='todo.userlist'),
        ),
        migrations.AddField(
            model_name='userlist',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile_photos/default.jpg', upload_to='profile_photos/'),
        ),
    ]
