# Generated by Django 4.0.5 on 2022-07-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_userlist_followers_userlist_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile_photos/default.svg', upload_to='profile_photos/'),
        ),
    ]
